/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#ff5451',
        'surface-container-low': '#1c1b1b',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-tertiary-fixed-variant': '#930013',
        'secondary-container': '#00a572',
        'surface-dim': '#131313',
        'on-primary-container': '#0d0096',
        'surface-container': '#201f1f',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary-container': '#00311f',
        'surface-container-highest': '#353534',
        'on-tertiary-fixed': '#410004',
        'secondary-fixed-dim': '#4edea3',
        'surface-tint': '#c0c1ff',
        'tertiary-fixed': '#ffdad7',
        'inverse-surface': '#e5e2e1',
        'primary-fixed': '#e1e0ff',
        'surface': '#131313',
        'on-error': '#690005',
        'on-surface': '#e5e2e1',
        'primary': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'outline': '#908fa0',
        'on-tertiary': '#68000a',
        'surface-bright': '#3a3939',
        'tertiary': '#ffb3ad',
        'tertiary-fixed-dim': '#ffb3ad',
        'primary-container': '#8083ff',
        'on-secondary-fixed-variant': '#005236',
        'on-secondary': '#003824',
        'on-tertiary-container': '#5c0008',
        'on-secondary-fixed': '#002113',
        'on-surface-variant': '#c7c4d7',
        'on-primary': '#1000a9',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
        'outline-variant': '#464554',
        'secondary-fixed': '#6ffbbe',
        'inverse-on-surface': '#313030',
        'background': '#131313',
        'error-container': '#93000a',
        'primary-fixed-dim': '#c0c1ff',
        'secondary': '#4edea3',
        'inverse-primary': '#494bd6',
        'surface-container-high': '#2a2a2a',
        'error': '#ffb4ab',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'gutter': '16px',
        'base': '8px',
        'margin-desktop': '40px',
        'container-padding': '24px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'data-tabular': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'data-tabular': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
