/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Light theme (default)
        surface: {
          DEFAULT: "#FFFFFF",
          dim: "#cbdbf5",
          bright: "#f8f9ff",
          "container-lowest": "#ffffff",
          "container-low": "#eff4ff",
          container: "#F8FAFC",
          "container-high": "#dce9ff",
          "container-highest": "#d3e4fe",
          variant: "#d3e4fe",
        },
        "on-surface": {
          DEFAULT: "#0b1c30",
          variant: "#464554",
        },
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: {
          DEFAULT: "#767586",
          variant: "#c7c4d7",
        },
        primary: {
          DEFAULT: "#059669",
          container: "#10b981",
          fixed: "#d1fae5",
          "fixed-dim": "#6ee7b7",
          "inverse": "#6ee7b7",
          "on-primary": "#ffffff",
          "on-primary-container": "#fffbff",
          "on-primary-fixed": "#022c22",
          "on-primary-fixed-variant": "#047857",
        },
        secondary: {
          DEFAULT: "#006c49",
          container: "#6cf8bb",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
          "on-secondary": "#ffffff",
          "on-secondary-container": "#00714d",
          "on-secondary-fixed": "#002113",
          "on-secondary-fixed-variant": "#005236",
        },
        tertiary: {
          DEFAULT: "#b90538",
          container: "#dc2c4f",
          fixed: "#ffdadb",
          "fixed-dim": "#ffb2b7",
          "on-tertiary": "#ffffff",
          "on-tertiary-container": "#fffbff",
          "on-tertiary-fixed": "#40000d",
          "on-tertiary-fixed-variant": "#92002a",
        },
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
          "on-error": "#ffffff",
          "on-error-container": "#93000a",
        },
        background: "#f8f9ff",
        "on-background": "#0b1c30",
      },
      fontFamily: {
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          '"Roboto"',
          '"Oxygen"',
          '"Ubuntu"',
          '"Cantarell"',
          '"Fira Sans"',
          '"Droid Sans"',
          '"Helvetica Neue"',
          "sans-serif",
        ],
      },
      fontSize: {
        "display-lg": ["3.6rem", { lineHeight: "4.2rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["2.4rem", { lineHeight: "3rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.8rem", { lineHeight: "2.4rem", fontWeight: "600" }],
        "headline-md": ["1.8rem", { lineHeight: "2.4rem", fontWeight: "600" }],
        "body-lg": ["1.35rem", { lineHeight: "2.1rem", fontWeight: "400" }],
        "body-md": ["1.2rem", { lineHeight: "1.8rem", fontWeight: "400" }],
        "label-md": ["1.05rem", { lineHeight: "1.5rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["0.9rem", { lineHeight: "1.2rem", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-tabular": ["1.2rem", { lineHeight: "1.8rem", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      spacing: {
        gutter: "16px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "container-padding": "24px",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [],
}
