// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTransactions():Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function SaveTransaction(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;
