// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function ExportProfileData(arg1) {
  return window['go']['main']['App']['ExportProfileData'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
