// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profile} from '../models';

export function CreateProfile(arg1:profile.Profile):Promise<profile.Profile>;

export function ExportProfileData(arg1:string):Promise<profile.ProfileExport>;

export function Greet(arg1:string):Promise<string>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function RenameProfile(arg1:string,arg2:string):Promise<profile.Profile>;

export function UpdateProfile(arg1:profile.Profile):Promise<profile.Profile>;
