// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {income} from '../models';
import {profile} from '../models';

export function CreateIncomeEntry(arg1:string,arg2:income.Entry):Promise<income.Entry>;

export function CreateIncomeStream(arg1:income.Stream):Promise<income.Stream>;

export function CreateProfile(arg1:profile.Profile):Promise<profile.Profile>;

export function DeleteIncomeAttachment(arg1:string,arg2:string,arg3:string):Promise<income.Entry>;

export function DeleteIncomeEntry(arg1:string,arg2:string):Promise<void>;

export function DeleteIncomeStream(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportProfileData(arg1:string):Promise<profile.ProfileExport>;

export function Greet(arg1:string):Promise<string>;

export function ListIncomeEntries(arg1:string,arg2:string,arg3:string):Promise<Array<income.Entry>>;

export function ListIncomeStreams(arg1:string):Promise<Array<income.Stream>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ReadIncomeAttachment(arg1:string):Promise<Array<number>>;

export function RenameProfile(arg1:string,arg2:string):Promise<profile.Profile>;

export function SaveIncomeAttachment(arg1:string,arg2:string,arg3:string,arg4:Array<number>):Promise<string>;

export function UpdateIncomeEntry(arg1:string,arg2:income.Entry):Promise<income.Entry>;

export function UpdateIncomeStream(arg1:income.Stream):Promise<income.Stream>;

export function UpdateProfile(arg1:profile.Profile):Promise<profile.Profile>;
