// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateIncomeEntry(arg1, arg2) {
  return window['go']['main']['App']['CreateIncomeEntry'](arg1, arg2);
}

export function CreateIncomeStream(arg1) {
  return window['go']['main']['App']['CreateIncomeStream'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteIncomeAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteIncomeAttachment'](arg1, arg2, arg3);
}

export function DeleteIncomeEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteIncomeEntry'](arg1, arg2);
}

export function DeleteIncomeStream(arg1, arg2) {
  return window['go']['main']['App']['DeleteIncomeStream'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportProfileData(arg1) {
  return window['go']['main']['App']['ExportProfileData'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListIncomeEntries(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListIncomeEntries'](arg1, arg2, arg3);
}

export function ListIncomeStreams(arg1) {
  return window['go']['main']['App']['ListIncomeStreams'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ReadIncomeAttachment(arg1) {
  return window['go']['main']['App']['ReadIncomeAttachment'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function SaveIncomeAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveIncomeAttachment'](arg1, arg2, arg3, arg4);
}

export function UpdateIncomeEntry(arg1, arg2) {
  return window['go']['main']['App']['UpdateIncomeEntry'](arg1, arg2);
}

export function UpdateIncomeStream(arg1) {
  return window['go']['main']['App']['UpdateIncomeStream'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
