// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTransactions() {
  return window['go']['main']['App']['GetTransactions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveTransaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTransaction'](arg1, arg2, arg3);
}
